# PostgreSQL. Versions 9.1 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: muqawiloon_dev
  username: postgres
  password: <%=ENV['RDS_PASSWORD_STG']%>
  host: localhost
  port: <%= ENV['RDS_PORT'] %>

staging:
  <<: *default
  database: muqawiloon_dev
  username: postgres
  password: <%=ENV['RDS_PASSWORD_STG']%>
  host: localhost
  port: <%= ENV['RDS_PORT'] %>
test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: muqawiloon_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
